server:
  port: 8092

logging:
  level:
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://sso.local:8090/auth/realms/demo